<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../A320Copilot.Bridge/A320Copilot.Bridge.csproj" />
    <ProjectReference Include="../A320Copilot.Domain/A320Copilot.Domain.csproj" />
  </ItemGroup>
</Project>
